menu:
- {name: 'about', url: '/'}
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv/resume.pdf', target: '_blank'}

people:
- {name: 'Primary Investigator', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/primary-investigator.jpg', url: 'primary-investigator'}
- {name: 'Lab Technician', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/lab-technician.jpg', url: 'lab-technician'}
- {name: 'Graduate Student', title: 'Researcher', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/graduate-student.jpg', url: 'graduate-student'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/aaminaa01'}
- {icon: 'google-scholar', link: 'https://scholar.google.com/citations?hl=en&view_op=list_works&gmla=AKzYXQ3_Eq7gv8XIz5-HT32vZnfBsoJOV22ZnL8HfSHb1D7xCSQ34RuO_sQg-pj5ckIgSdMKMCUDaiERz6MgKQ&user=tqisD5MAAAAJ'}
- {icon: 'bluesky', link: 'https://bsky.app/profile/aaminaaaa.bsky.social'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/aamina-binte-khurram/'}
- {icon: 'medium', link: 'https://medium.com/@aaminew'}
- {icon: 'paper-plane', link: 'mailto:aaminabintekhurram@gmail.com'}


contacts:
- {name: 'Dr. Academia', title: 'Professor', department: 'Physics & Astronomy', institution: 'Some University', institution_address: '1 Main Street, Canada', phone: '(000) 000-0000', email: 'hello@university.edu', office: 'Science Building 505', image: 'assets/img/contact.jpg'}
